import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <section>
          <div className="text-center">
            <p>
              {" "}
              <a
                href="https://www.harmanpreetsingh.me/"
                target="_blank"
                rel="noopener noreferrer"
              >
                Created by{" "}
                <span className="text-blue-500 hover:underline">
                  Harmanpreet Singh
                </span>
              </a>
            </p>
          </div>
        </section>
      </body>
    </html>
  );
}
